# Generated by Django 3.2 on 2023-01-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order_items',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_items',
            field=models.ManyToManyField(related_name='order_items', to='api.OrderItem'),
        ),
    ]
